name: jlpt_study
description: "A JLPT and Kana spaced-repetition study app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.4.3
  path: ^1.9.1
  sqflite_common_ffi: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - assets/database/jlpt_study_master.sqlite
    - assets/data/
    - assets/data/practice/jlpt_practice_n5_vocab_clean.json
    - assets/data/practice/
    - assets/audio/kana/
    - assets/branding/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/branding/jlpt_study_icon.png"
  adaptive_icon_background: "#F6F1E8"
  adaptive_icon_foreground: "assets/branding/jlpt_study_launcher_foreground.png"

flutter_native_splash:
  color: "#F6F1E8"
  image: assets/branding/jlpt_study_native_splash.png
  android: true
  ios: false
  web: false

  android_12:
    color: "#F6F1E8"
    image: assets/branding/jlpt_study_native_splash.png
    icon_background_color: "#F6F1E8"
